
stages:
  - terraforminit
  - terraformplan
  - terraformapply

variables:
  WORKING_DIR: "Terraform/"
  BACKEND_KEY: "movieexplorer-prod.tfstate"
  RESOURCE_GROUP: "movie-explorer-rg"
  STORAGE_ACCOUNT: "lewisfuncstorage"
  CONTAINER_NAME: "tfstate"

terraforminit:
  stage: terraforminit
  image: mcr.microsoft.com/azure-cli
  rules:
  - when: manual
  before_script:
  - apt-get update && apt-get install -y curl jq python3-pip unzip
  - pip3 install azure-cli
  - curl -fsSL https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip -o terraform.zip
  - unzip terraform.zip && mv terraform /usr/local/bin/ && terraform -version
  - az login --service-principal \
      --username "$AZURE_CLIENT_ID" \
      --password "$AZURE_CLIENT_SECRET" \
      --tenant "$AZURE_TENANT_ID"
  script:
    - echo "Initializing Terraform..."
    - terraform -chdir=$WORKING_DIR init \
        -backend-config="resource_group_name=$RESOURCE_GROUP" \
        -backend-config="storage_account_name=$STORAGE_ACCOUNT" \
        -backend-config="container_name=$CONTAINER_NAME" \
        -backend-config="key=$BACKEND_KEY" \
        -reconfigure -upgrade
    - echo "Validating Terraform..."
    - terraform -chdir=$WORKING_DIR validate
    - echo "Terraform initialized and validated."
    - echo "Formatting Terraform files..."
    - terraform -chdir=$WORKING_DIR fmt -recursive
    - echo "Terraform files formatted."

terraformplan:
  stage: terraformplan  
  needs:
    - terraforminit  
  rules:
  - when: on_success  
  image: hashicorp/terraform:latest
  script:
    - echo "Planning Terraform..."
    - terraform -chdir=$WORKING_DIR plan \
        -var="subscription_id=$SUBSCRIPTION_ID" \
        -var="sql_admin_username=$SQL_ADMIN_USERNAME" \
        -var="sql_admin_password=$SQL_ADMIN_PASSWORD"
    - echo "Terraform plan completed."

terraformapply:
  stage: terraformapply
  needs:
    - terraformplan
  rules:
  - when: on_success
  image: hashicorp/terraform:latest
  script:
    - echo "Applying Terraform..."
    - terraform -chdir=$WORKING_DIR apply \
        -auto-approve \
        -var="subscription_id=$SUBSCRIPTION_ID" \
        -var="sql_admin_username=$SQL_ADMIN_USERNAME" \
        -var="sql_admin_password=$SQL_ADMIN_PASSWORD"
    - echo "Terraform applied successfully."    
