workflow:
  rules:
    - when: always  # Always create a pipeline on push

stages:
  - noop

noop_job:
  stage: noop
  script:
    - echo "This is a placeholder job to make the pipeline visible."
  when: manual
  rules:
    - when: always

include:
  - local: 'GitLab/.gitlab-ci-core.yml'
  - local: 'GitLab/.gitlab-ci-terraform.yml'
  - local: 'GitLab/.gitlab-ci-deployapp.yml'
  - local: 'GitLab/.gitlab-ci-destroy.yml'
