
stages:
  - terraforminit
  - terraformplan
  - terraformapply

variables:
  WORKING_DIR: "Terraform/"
  BACKEND_KEY: "movieexplorer-prod.tfstate"
  RESOURCE_GROUP: "movie-explorer-rg"
  STORAGE_ACCOUNT: "lewisfuncstorage"
  CONTAINER_NAME: "tfstate"

terraforminit:
  stage: terraforminit
  image: hashicorp/terraform:latest
  rules:
  - when: manual
  before_script:
    - apk add --no-cache bash curl jq python3 py3-pip
    - pip3 install azure-cli
    - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
  script:
    - echo "Initializing Terraform..."
    - terraform -chdir=$WORKING_DIR init \
        -backend-config="resource_group_name=$RESOURCE_GROUP" \
        -backend-config="storage_account_name=$STORAGE_ACCOUNT" \
        -backend-config="container_name=$CONTAINER_NAME" \
        -backend-config="key=$BACKEND_KEY" \
        -reconfigure -upgrade
    - echo "Validating Terraform..."
    - terraform -chdir=$WORKING_DIR validate
    - echo "Terraform initialized and validated."
    - echo "Formatting Terraform files..."
    - terraform -chdir=$WORKING_DIR fmt -recursive
    - echo "Terraform files formatted."

terraformplan:
  stage: terraformplan  
  needs:
    - terraforminit  
  rules:
  - when: success  
  image: hashicorp/terraform:latest
  script:
    - echo "Planning Terraform..."
    - terraform -chdir=$WORKING_DIR plan \
        -var="subscription_id=$SUBSCRIPTION_ID" \
        -var="sql_admin_username=$SQL_ADMIN_USERNAME" \
        -var="sql_admin_password=$SQL_ADMIN_PASSWORD"
    - echo "Terraform plan completed."

terraformapply:
  stage: terraformapply
  needs:
    - terraformplan
  rules:
  - when: success
  image: hashicorp/terraform:latest
  script:
    - echo "Applying Terraform..."
    - terraform -chdir=$WORKING_DIR apply \
        -auto-approve \
        -var="subscription_id=$SUBSCRIPTION_ID" \
        -var="sql_admin_username=$SQL_ADMIN_USERNAME" \
        -var="sql_admin_password=$SQL_ADMIN_PASSWORD"
    - echo "Terraform applied successfully."    
