stages:
  - rg
  - storage
  - container
  - acr
  - terraforminit
  - terraformplan
  - terraformapply
  - deployapp
  - destroy

include:
  - local: '.gitlab-ci-core.yml'
  - local: '.gitlab-ci-terraform.yml'
  - local: '.gitlab-ci-deployapp.yml'
  - local: '.gitlab-ci-destroy.yml'
