workflow:
  rules:
    - if: '$RUN_MAIN_TF == "true"'
      when: always
    - when: never

stages:
  - terraforminit
  - terraformplan
  - terraformapply

variables:
  WORKING_DIR: "Terraform/"
  BACKEND_KEY: "movieexplorer-prod.tfstate"
  RESOURCE_GROUP: "movie-explorer-rg"
  STORAGE_ACCOUNT: "lewisfuncstorage"
  CONTAINER_NAME: "tfstate"

terraforminit:
  stage: terraforminit
  image: ubuntu:22.04
  before_script:
    - apt-get update && apt-get install -y curl jq python3-pip unzip gnupg software-properties-common
    - pip3 install azure-cli
    - curl -fsSL https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip -o terraform.zip
    - unzip terraform.zip && mv terraform /usr/local/bin/terraform && terraform -version
    - az login --service-principal --username "$AZURE_CLIENT_ID" --password "$AZURE_CLIENT_SECRET_GITLAB" --tenant "$AZURE_TENANT_ID"
  script:
    - terraform -chdir=$WORKING_DIR init -backend-config="resource_group_name=$RESOURCE_GROUP" -backend-config="storage_account_name=$STORAGE_ACCOUNT" -backend-config="container_name=$CONTAINER_NAME" -backend-config="key=$BACKEND_KEY" -reconfigure -upgrade
    - terraform -chdir=$WORKING_DIR validate
    - terraform -chdir=$WORKING_DIR fmt -recursive

terraformplan:
  stage: terraformplan  
  needs: [terraforminit]  
  image: hashicorp/terraform:latest
  script:
    - terraform -chdir=$WORKING_DIR plan -var="subscription_id=$SUBSCRIPTION_ID" -var="sql_admin_username=$SQL_ADMIN_USERNAME" -var="sql_admin_password=$SQL_ADMIN_PASSWORD"

terraformapply:
  stage: terraformapply
  needs: [terraformplan]
  image: hashicorp/terraform:latest
  script:
    - terraform -chdir=$WORKING_DIR apply -auto-approve -var="subscription_id=$SUBSCRIPTION_ID" -var="sql_admin_username=$SQL_ADMIN_USERNAME" -var="sql_admin_password=$SQL_ADMIN_PASSWORD"
