workflow:
  rules:
    - if: '$RUN_DESTROY == "true"'
      when: manual
stages:
  - destroy

variables:
  WORKING_DIR: "Terraform/"
  BACKEND_KEY: "movieexplorer-prod.tfstate"
  RESOURCE_GROUP: "movie-explorer-rg"
  STORAGE_ACCOUNT: "lewisfuncstorage"
  CONTAINER_NAME: "tfstate"

terraform_destroy:
  stage: destroy
  image: ubuntu:22.04
  before_script:
    - apt-get update && apt-get install -y curl jq python3-pip unzip gnupg software-properties-common
    - pip3 install azure-cli
    - curl -fsSL https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip -o terraform.zip
    - unzip terraform.zip && mv terraform /usr/local/bin/terraform && terraform -version
    - az login --service-principal --username "$AZURE_CLIENT_ID" --password "$AZURE_CLIENT_SECRET_GITLAB" --tenant "$AZURE_TENANT_ID"
  script:
    - echo "Initializing Terraform..."
    - terraform -chdir=$WORKING_DIR init \
        -backend-config="resource_group_name=$RESOURCE_GROUP" \
        -backend-config="storage_account_name=$STORAGE_ACCOUNT" \
        -backend-config="container_name=$CONTAINER_NAME" \
        -backend-config="key=$BACKEND_KEY" \
        -reconfigure -upgrade \
        -var="sql_admin_username=$SQL_ADMIN_USERNAME" \
        -var="sql_admin_password=$SQL_ADMIN_PASSWORD" \
        -var="subscription_id=$SUBSCRIPTION_ID"
    - echo "Showing current Terraform state..."
    - terraform -chdir=$WORKING_DIR show
    - echo "Destroying infrastructure..."
    - terraform -chdir=$WORKING_DIR destroy -auto-approve \
        -var="sql_admin_username=$SQL_ADMIN_USERNAME" \
        -var="sql_admin_password=$SQL_ADMIN_PASSWORD" \
        -var="subscription_id=$SUBSCRIPTION_ID"
    - echo "Terraform destroy complete."
